---
- name: Update apt cache
  apt:
    update_cache: yes
    cache_valid_time: 3600

- name: Install common packages
  apt:
    name:
      - python3
      - python3-pip
      - acl
      - curl
      - wget
      - gnupg2
    state: present